version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    build: . # specify the directory of the Dockerfile
    ports:
      - "5200:4200" # specify port forewarding
    volumes:
      - .:/angular/app # this will enable changes made to the angular app reflect in the container
